
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2.1'
version_full = 'bd463ab394a421486681ff06f07c94c87cdfccf3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

